# Generated by Django 4.2.4 on 2024-01-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='created_at',
        ),
    ]
