# Generated by Django 4.2.4 on 2024-01-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_remove_clients_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='created_at',
            field=models.DateTimeField(auto_now=True, unique=True),
        ),
    ]
